package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"text/tabwriter"
)

const usage = `hidemail — iCloud Hide My Email CLI

Usage:
  hidemail auth              Connect to iCloud (opens a browser to grab your session)
  hidemail gen [flags]       Generate a new Hide My Email address
  hidemail list [flags]      List your Hide My Email addresses
  hidemail logout            Delete the stored iCloud session from this machine

gen flags:
  --label   string  label for the address (default "hidemail cli")
  --note    string  note for the address (default "Generated by hidemail")
  --no-reserve      only generate a candidate, don't claim it

list flags:
  --json            output raw JSON
  --active          only show active addresses
  --match  string   filter by regexp over address/label
`

func main() {
	if len(os.Args) < 2 {
		fmt.Print(usage)
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "auth":
		err = authWeb()
	case "gen", "g", "generate":
		err = cmdGen(os.Args[2:])
	case "list", "ls", "l":
		err = cmdList(os.Args[2:])
	case "logout", "signout":
		err = cmdLogout()
	case "-h", "--help", "help":
		fmt.Print(usage)
		return
	default:
		fmt.Fprintf(os.Stderr, "unknown command %q\n\n%s", os.Args[1], usage)
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func cmdLogout() error {
	existed, err := clearCookies()
	if err != nil {
		return err
	}
	if existed {
		fmt.Println("Signed out — stored iCloud session deleted.")
	} else {
		fmt.Println("Already signed out — no stored session.")
	}
	return nil
}

func cmdGen(args []string) error {
	fs := flag.NewFlagSet("gen", flag.ExitOnError)
	label := fs.String("label", "hidemail cli", "")
	note := fs.String("note", "Generated by hidemail", "")
	noReserve := fs.Bool("no-reserve", false, "")
	fs.Parse(args)

	labeled := false
	fs.Visit(func(f *flag.Flag) {
		if f.Name == "label" || f.Name == "note" {
			labeled = true
		}
	})

	c, err := NewClient()
	if err != nil {
		return err
	}
	hme, err := c.Generate()
	if err != nil {
		return err
	}
	if !*noReserve {
		if err := c.Reserve(hme, *label, *note); err != nil {
			return fmt.Errorf("generated %s but couldn't reserve it: %w", hme, err)
		}
	}
	fmt.Println(hme)
	if tryCopy(hme) {
		fmt.Fprintln(os.Stderr, "(copied to clipboard)")
	}
	if *noReserve {
		fmt.Fprintln(os.Stderr, "(candidate only — not reserved; it won't forward mail)")
	}
	if !labeled {
		fmt.Fprintln(os.Stderr, `(tip: add --label "what it's for" so you can tell your addresses apart later)`)
	}
	return nil
}

func cmdList(args []string) error {
	fs := flag.NewFlagSet("list", flag.ExitOnError)
	asJSON := fs.Bool("json", false, "")
	active := fs.Bool("active", false, "")
	match := fs.String("match", "", "")
	fs.Parse(args)

	var re *regexp.Regexp
	if *match != "" {
		var err error
		if re, err = regexp.Compile(*match); err != nil {
			return fmt.Errorf("bad --match regexp: %w", err)
		}
	}

	c, err := NewClient()
	if err != nil {
		return err
	}
	all, err := c.List()
	if err != nil {
		return err
	}

	out := all[:0]
	for _, a := range all {
		if *active && !a.IsActive {
			continue
		}
		if re != nil && !re.MatchString(a.Hme) && !re.MatchString(a.Label) {
			continue
		}
		out = append(out, a)
	}

	if *asJSON {
		b, _ := json.MarshalIndent(out, "", "  ")
		fmt.Println(string(b))
		return nil
	}
	tw := tabwriter.NewWriter(os.Stdout, 0, 2, 2, ' ', 0)
	fmt.Fprintln(tw, "ADDRESS\tLABEL\tACTIVE")
	for _, a := range out {
		state := "no"
		if a.IsActive {
			state = "yes"
		}
		fmt.Fprintf(tw, "%s\t%s\t%s\n", a.Hme, a.Label, state)
	}
	tw.Flush()
	return nil
}
